spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpatestingdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}      # from environment variable
    password: ${DB_PASSWORD}      # from environment variable
  jpa:
    hibernate:
      ddl-auto: none              # never auto-change schema in prod
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  error:
    include-methods: false

logging:
  level:
    root: warn
    org.springframework.boot: info